"""baseline

Revision ID: 2a64a5a06e1d
Revises: 
Create Date: 2026-09-03 02:39:32.794420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a64a5a06e1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('base_ccy', sa.String(length=3), nullable=False),
    sa.Column('quote_ccy', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index('idx_prices_pair_timestamp', ['base_ccy', 'quote_ccy', 'timestamp'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('nationalities', sa.Text(), nullable=True),
    sa.Column('tax_residencies', sa.Text(), nullable=True),
    sa.Column('countries_of_interest', sa.Text(), nullable=True),
    sa.Column('phone_country_code', sa.String(length=5), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=100), nullable=True),
    sa.Column('address_postal_code', sa.String(length=20), nullable=True),
    sa.Column('address_country', sa.String(length=2), nullable=True),
    sa.Column('tax_id_number', sa.String(length=50), nullable=True),
    sa.Column('is_us_person', sa.Boolean(), nullable=True),
    sa.Column('tos_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('privacy_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('tos_version', sa.String(length=10), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.String(length=20), nullable=True),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index('idx_audit_logs_actor_created', ['actor_user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_audit_logs_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)

    op.create_table('bug_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bug_reports', schema=None) as batch_op:
        batch_op.create_index('idx_bug_reports_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_bug_reports_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bug_reports_user_id'), ['user_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('min_wc_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('account_currency', sa.String(length=3), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('starting_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('idx_accounts_workspace_active', ['workspace_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('bug_report_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bug_report_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bug_report_id'], ['bug_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bug_report_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bug_report_media_bug_report_id'), ['bug_report_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('idx_categories_workspace_type', ['workspace_id', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('funds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allocation_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.create_index('idx_funds_workspace_active', ['workspace_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_funds_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assumptions_json', sa.Text(), nullable=False),
    sa.Column('monthly_expenses_total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('card_name', sa.String(length=255), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('card_network', sa.String(length=50), nullable=True),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index('idx_cards_account', ['account_id'], unique=False)
        batch_op.create_index('idx_cards_workspace_active', ['workspace_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('fund_accounts',
    sa.Column('fund_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('allocation_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fund_id', 'account_id')
    )
    op.create_table('fund_allocation_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('fund_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('allocation_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('override_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_allocation_overrides', schema=None) as batch_op:
        batch_op.create_index('idx_overrides_workspace_fund_period', ['workspace_id', 'fund_id', 'year', 'month'], unique=True)
        batch_op.create_index(batch_op.f('ix_fund_allocation_overrides_fund_id'), ['fund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_allocation_overrides_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('projection_assumptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projection_assumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projection_assumptions_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('projection_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('metric_key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projection_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projection_results_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('subcategories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.create_index('idx_subcategories_category', ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcategories_category_id'), ['category_id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('linked_account_id', sa.String(length=36), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['linked_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index('idx_payment_methods_workspace_active', ['workspace_id', 'is_active'], unique=False)
        batch_op.create_index('idx_payment_methods_workspace_type', ['workspace_id', 'method_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('recurring_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('payee', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('subcategory_id', sa.String(length=36), nullable=True),
    sa.Column('fund_id', sa.String(length=36), nullable=True),
    sa.Column('payment_method_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('from_account_id', sa.String(length=36), nullable=True),
    sa.Column('to_account_id', sa.String(length=36), nullable=True),
    sa.Column('from_currency', sa.String(length=3), nullable=True),
    sa.Column('to_currency', sa.String(length=3), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=19, scale=6), nullable=True),
    sa.Column('source_fund_id', sa.String(length=36), nullable=True),
    sa.Column('dest_fund_id', sa.String(length=36), nullable=True),
    sa.Column('transfer_fee', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('fee_category_id', sa.String(length=36), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('next_occurrence', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dest_fund_id'], ['funds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fee_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['source_fund_id'], ['funds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_recurring_next_occurrence', ['workspace_id', 'next_occurrence'], unique=False)
        batch_op.create_index('idx_recurring_workspace_active', ['workspace_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_transactions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('payee', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('import_hash', sa.String(length=64), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('subcategory_id', sa.String(length=36), nullable=True),
    sa.Column('fund_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('source_fund_id', sa.String(length=36), nullable=True),
    sa.Column('dest_fund_id', sa.String(length=36), nullable=True),
    sa.Column('payment_method_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dest_fund_id'], ['funds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['source_fund_id'], ['funds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_category', ['category_id'], unique=False)
        batch_op.create_index('idx_transactions_dest_fund', ['dest_fund_id'], unique=False)
        batch_op.create_index('idx_transactions_fund', ['fund_id'], unique=False)
        batch_op.create_index('idx_transactions_import_hash', ['workspace_id', 'import_hash'], unique=False)
        batch_op.create_index('idx_transactions_payment_method', ['payment_method_id'], unique=False)
        batch_op.create_index('idx_transactions_source_fund', ['source_fund_id'], unique=False)
        batch_op.create_index('idx_transactions_type', ['workspace_id', 'type'], unique=False)
        batch_op.create_index('idx_transactions_workspace_timestamp', ['workspace_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_fund_id'), ['fund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_payment_method_id'), ['payment_method_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_subcategory_id'), ['subcategory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('postings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('posting_currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.create_index('idx_postings_account', ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postings_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postings_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('transaction_tags',
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('tag_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_tags')
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postings_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_postings_account_id'))
        batch_op.drop_index('idx_postings_account')

    op.drop_table('postings')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_subcategory_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_payment_method_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_fund_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))
        batch_op.drop_index('idx_transactions_workspace_timestamp')
        batch_op.drop_index('idx_transactions_type')
        batch_op.drop_index('idx_transactions_source_fund')
        batch_op.drop_index('idx_transactions_payment_method')
        batch_op.drop_index('idx_transactions_import_hash')
        batch_op.drop_index('idx_transactions_fund')
        batch_op.drop_index('idx_transactions_dest_fund')
        batch_op.drop_index('idx_transactions_category')

    op.drop_table('transactions')
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_transactions_workspace_id'))
        batch_op.drop_index('idx_recurring_workspace_active')
        batch_op.drop_index('idx_recurring_next_occurrence')

    op.drop_table('recurring_transactions')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_workspace_id'))
        batch_op.drop_index('idx_payment_methods_workspace_type')
        batch_op.drop_index('idx_payment_methods_workspace_active')

    op.drop_table('payment_methods')
    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcategories_category_id'))
        batch_op.drop_index('idx_subcategories_category')

    op.drop_table('subcategories')
    with op.batch_alter_table('projection_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projection_results_scenario_id'))

    op.drop_table('projection_results')
    with op.batch_alter_table('projection_assumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projection_assumptions_scenario_id'))

    op.drop_table('projection_assumptions')
    with op.batch_alter_table('fund_allocation_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_allocation_overrides_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_fund_allocation_overrides_fund_id'))
        batch_op.drop_index('idx_overrides_workspace_fund_period')

    op.drop_table('fund_allocation_overrides')
    op.drop_table('fund_accounts')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_workspace_id'))
        batch_op.drop_index('idx_cards_workspace_active')
        batch_op.drop_index('idx_cards_account')

    op.drop_table('cards')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_workspace_id'))

    op.drop_table('scenarios')
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funds_workspace_id'))
        batch_op.drop_index('idx_funds_workspace_active')

    op.drop_table('funds')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_workspace_id'))
        batch_op.drop_index('idx_categories_workspace_type')

    op.drop_table('categories')
    with op.batch_alter_table('bug_report_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bug_report_media_bug_report_id'))

    op.drop_table('bug_report_media')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_workspace_id'))
        batch_op.drop_index('idx_accounts_workspace_active')

    op.drop_table('accounts')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_user_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('bug_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bug_reports_user_id'))
        batch_op.drop_index('idx_bug_reports_user_status')
        batch_op.drop_index('idx_bug_reports_status_created')

    op.drop_table('bug_reports')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index('idx_audit_logs_target')
        batch_op.drop_index('idx_audit_logs_actor_created')
        batch_op.drop_index('idx_audit_logs_action_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    op.drop_table('tags')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index('idx_prices_pair_timestamp')

    op.drop_table('prices')
    # ### end Alembic commands ###
